pipeline {
    agent {
        docker { 
            image 'maven:3.9.6-eclipse-temurin-21'
            args '-v maven-repo:/home/jenkins/.m2 -u 501:20'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh """
                   mvn -version
                   ls
                   // Use /home/jenkins/.m2/repository (mounted volume) instead of /root/.m2
                   mvn -Dmaven.repo.local=/home/jenkins/.m2/repository -B clean package
                """
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -Dmaven.repo.local=/home/jenkins/.m2/repository test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
