pipeline {
    agent {
        docker { 
            image 'maven:3.9.6-eclipse-temurin-21'
            args '-v maven-repo:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh """
                   mvn -version
                   ls
                   mvn -B -DskipTests clean package
                """
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh 'chmod +x ./jenkins/scripts/deliver.sh'
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
