pipeline {
    agent {
        docker {
            image 'maven:3.9.6-jdk-21' // Valid image with JDK 21
            args '-v $HOME/.m2:/root/.m2' // Fix volume path for macOS
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
