name: Java CI/CD

on: [push]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven (skip tests)
      run: mvn -B -DskipTests clean package

    - name: Run Tests
      run: mvn test

    - name: Archive Test Results
      uses: actions/upload-artifact@v4  # Updated to v4
      if: always()
      with:
        name: test-results
        path: target/surefire-reports/*.xml

    - name: Deliver
      run: |
        chmod +x ./jenkins/scripts/deliver.sh
        ./jenkins/scripts/deliver.sh
